services:   
    api:
        build: .
        restart: unless-stopped
        env_file:
            - ./local.env
        ports:
            - "8018:80"
        container_name: assets-manager-api
    db:
        image: "mcr.microsoft.com/mssql/server"
        restart: unless-stopped
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1442:1433"
        container_name: assets-manager-db